[document]
title = "Project 2"
author = ["Amund Midtgård Raniseth", "Anna Stray Rongve", "Knut Magnus Aasrud"]
date = "today"

# This will be supported in Doctor v0.2.0
# number-sections = true

[build]
pdf-engine = "pdflatex"
