[meta]
title = "Project 2"
author = ["Amund Midtgård Raniseth", "Anna Stray Rongve", "Knut Magnus Aasrud"]
date = "today"

[style]
number-sections = true
document-class = "report"

[bib]
bibliography-title = "References"
csl = "apa"

[build]
engine = "pdflatex"
filename = "report"

[latex]
packages = ["placeins"]
