[meta]
title = "Project 2"
author = ["Amund Midtgård Raniseth", "Anna Stray Rongve", "Knut Magnus Aasrud"]
date = "today"

[style]
number-sections = true

[bib]
bibliography-title = "References"

[build]
engine = "tectonic"
filename = "report"
